export const veiculos = [
  {
    id: 1,
    modelo: "Fusca",
    marca: "Volkswagen",
    ano: 1978,
    preco: 25000,
    cor: "Amarelo",
    quilometragem: 150000,
    tipo: "Sedan",
    combustivel: "Gasolina",
    imagemUrl: "https://lartbr.com.br/wp-content/uploads/2023/08/IMG_5376.jpg",
    disponivel: true,
  },
  {
    id: 2,
    modelo: "Civic",
    marca: "Honda",
    ano: 2022,
    preco: 120000,
    cor: "Preto",
    quilometragem: 20000,
    tipo: "Sedan",
    combustivel: "Gasolina",
    imagemUrl:
      "https://cdn.autopapo.com.br/box/uploads/2018/01/12161836/honda-civic-201861.jpg",
    disponivel: true,
  },
  {
    id: 3,
    modelo: "Corolla",
    marca: "Toyota",
    ano: 2020,
    preco: 95000,
    cor: "Prata",
    quilometragem: 30000,
    tipo: "Sedan",
    combustivel: "Flex",
    imagemUrl:
      "https://cdn.autopapo.com.br/box/uploads/2024/12/16114343/toyota-corolla-gr-sport-2025-branco-frente-parado.jpg",
    disponivel: false,
  },
  {
    id: 4,
    modelo: "Jeep Compass",
    marca: "Jeep",
    ano: 2021,
    preco: 135000,
    cor: "Cinza",
    quilometragem: 25000,
    tipo: "SUV",
    combustivel: "Diesel",
    imagemUrl:
      "https://www.jeep.com.br/content/dam/jeep/open-graph/jeep-og-compass-my23.webp",
    disponivel: true,
  },
  {
    id: 5,
    modelo: "Fiesta",
    marca: "Ford",
    ano: 2015,
    preco: 35000,
    cor: "Vermelho",
    quilometragem: 80000,
    tipo: "Hatch",
    combustivel: "Flex",
    imagemUrl:
      "https://www.blogauto.com.br/wp-content/2012/01/Ford-Fiesta-RoCam.jpg",
    disponivel: false,
  },
  {
    id: 6,
    modelo: "ASX",
    marca: "Mitsubishi",
    ano: 2019,
    preco: 115000,
    cor: "Prata",
    quilometragem: 40000,
    tipo: "SUV",
    combustivel: "Diesel",
    imagemUrl:
      "https://quatrorodas.abril.com.br/wp-content/uploads/2016/11/56df0f1e0e21630a3e15df58277281_582635_0983_asx2016_murilomattos_2016_edit.jpeg?quality=70&strip=all&strip=all",
    disponivel: false,
  },
  {
    id: 7,
    modelo: "Onix",
    marca: "Chevrolet",
    ano: 2023,
    preco: 70000,
    cor: "Branco",
    quilometragem: 5000,
    tipo: "Hatch",
    combustivel: "Flex",
    imagemUrl:
      "https://jorlan.com/df/uploads/products/versions/gmcwh2035-pg020-mdv-1ec48-1ls-lhd-gaz.png",
    disponivel: true,
  },
  {
    id: 8,
    modelo: "Renegade",
    marca: "Jeep",
    ano: 2020,
    preco: 95000,
    cor: "Azul",
    quilometragem: 25000,
    tipo: "SUV",
    combustivel: "Flex",
    imagemUrl:
      "https://www.jeep.com.br//renegade/asset/versoes/longitude/jeep-renegade-longitude-carbon-black.webp",
    disponivel: true,
  },
  {
    id: 9,
    modelo: "A3",
    marca: "Audi",
    ano: 2022,
    preco: 150000,
    cor: "Cinza",
    quilometragem: 15000,
    tipo: "Sedan",
    combustivel: "Gasolina",
    imagemUrl:
      "https://production.autoforce.com/uploads/version/profile_image/10036/model_main_webp_comprar-performance-black-40-tfsi-s-tronic_7738837bc4.png.webp",
    disponivel: true,
  },
  {
    id: 10,
    modelo: "Porsche 911",
    marca: "Porsche",
    ano: 2021,
    preco: 500000,
    cor: "Preto",
    quilometragem: 10000,
    tipo: "Esportivo",
    combustivel: "Gasolina",
    imagemUrl:
      "https://cdn.motor1.com/images/mgl/0eKqYn/s1/2025-porsche-911-992.2-facelift.jpg",
    disponivel: false,
  },
];
